### ISSUE TITLE
mac上执行 ./build-openssl4android.sh有问题，帮忙看一下

### ISSUE THREAD

**Issue by ANDROIDTODO** [leenjewel/openssl_for_ios_and_android#12]
**********************************************
./build-openssl4android.sh: line 46: ./Configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
./build-openssl4android.sh: line 67: popd: directory stack empty
tar: Error opening archive: Failed to open 'openssl-1.0.2k.tar.gz'
./build-openssl4android.sh: line 31: pushd: openssl-1.0.2k: No such file or directory
**********************************************

**Comment by ANDROIDTODO** [comment]
我这边配置好了ANDROID_NDK的环境变量，还需要什么配置什么东西吗？新手，望告知一下，谢谢 @leenjewel

**Comment by leenjewel** [comment]
看你的报错信息是没有找到 Configure 这个文件，你下载的 openssl 版本是多少？是不是没有对应修改脚本里 openssl 的文件名，导致没有正确的解压？

**Comment by ANDROIDTODO** [comment]
恩，已经好了，但是执行sh ./build-openssl4android.sh 好久好久还没有执行完，不知道是不是正常的，
怎么样用libssl.a 和libcrypto.a 生成so库啊？新手一枚

**Comment by ANDROIDTODO** [comment]
@leenjewel 我想生成so库应该怎么弄。求大神告知

**Comment by leenjewel** [comment]
so 是最后生成在 Android 工程里的，OpenSSL 无法直接构建出 so ，具体的参看我最新写的 Example 吧
