### ISSUE TITLE
关于lib文件夹的问题

### ISSUE THREAD

**Issue by jiek233** [leenjewel/openssl_for_ios_and_android#14]
您好，我编译生成了一个output文件夹，和tools同级，tools下有一个libs文件夹，我想问下，我该把那个下面的armeabi复制到AndroidStudio工程呢？还有就是include/openssl该放到哪里？非常感谢

**Comment by jiek233** [comment]
还有想请教一个问题，我编译出来X:\openssl\output\android\openssl-armeabi文件夹下只有include和lib两个文件夹，这样对吗？因为我下载了您的output，发现比我的多，谢谢

**Comment by leenjewel** [comment]
这样编译出来是可以的

# -*-coding:uft-8 -*-
class Leen(Object):
    def  __init__(self):
        self.NAME = "李寅"
        self.MSN = "leenjewel@hotmail.com"
        self.EMAIL = "leenjewel@gmail.com"
        self.GitHub = "https://github.com/leenjewel"
        self.Blog = "http://leenjewel.github.io"
        self.QQ = 99603265

2017-07-18 15:26 GMT+08:00 jiek233 <notifications@github.com>:

**Comment by jiek233** [comment]
那就是说我要用output目录下的吗？非常感谢

**Comment by leenjewel** [comment]
我昨天写了一个 example 是专门示例 AndroidStudio 工程使用 OpenSSL 的，你可以 pull 一下代码看看

**Comment by jiek233** [comment]
非常感谢

**Comment by jiek233** [comment]
确认一下，只执行build-openssl4android就可以了吧？我暂时不需要curl（虽然并不知道是什么东西），感谢

**Comment by leenjewel** [comment]
是的
