### ISSUE TITLE
NDK version supported and linker issue

### ISSUE THREAD

**Issue by dkhanchopoulo** [leenjewel/openssl_for_ios_and_android#19]
Dear leenjewel,

kindly assist which NDK version I have use for build /build-openssl4android.sh

I tried with NDK-15 and g++ compiler

apps/ca.o: In function `do_body':
ca.c:(.text.unlikely+0x1108): undefined reference to `stdin'
apps/openssl.o: In function `main':
openssl.c:(.text.startup+0x1c8): undefined reference to `stpcpy'
openssl.c:(.text.startup+0x21c): undefined reference to `signal'
apps/ca.o: In function `do_body':
ca.c:(.text.unlikely+0x1108): undefined reference to `stdin'
apps/openssl.o: In function `main':
openssl.c:(.text.startup+0x1c8): undefined reference to `stpcpy'
openssl.c:(.text.startup+0x21c): undefined reference to `signal'

:ui_openssl.c:function open_console: error: undefined reference to 'stdin'

**Comment by dkhanchopoulo** [comment]
:pem_lib.c:function PEM_def_callback: error: undefined reference to 'stderr'

**Comment by dkhanchopoulo** [comment]
additionally, when I compile with boost::asio
I see
Error:(40) undefined reference to 'SSL_library_init'
Error:(42) undefined reference to 'OPENSSL_add_all_algorithms_noconf'

**Comment by dkhanchopoulo** [comment]
finally when I add zlib in my test project the only case is missing:
`  ../../../../libs/armeabi-v7a/libcrypto.a(cryptlib.o):cryptlib.c:function OPENSSL_showfatal: error: undefined reference to 'stderr'
  ../../../../libs/armeabi-v7a/libcrypto.a(pem_lib.o):pem_lib.c:function PEM_def_callback: error: undefined reference to 'stderr'
  ../../../../libs/armeabi-v7a/libcrypto.a(eng_openssl.o):eng_openssl.c:function openssl_load_privkey: error: undefined reference to 'stderr'
  ../../../../libs/armeabi-v7a/libcrypto.a(eng_openssl.o):eng_openssl.c:function test_rc4_init_key: error: undefined reference to 'stderr'
  ../../../../libs/armeabi-v7a/libcrypto.a(ui_openssl.o):ui_openssl.c:function close_console: error: undefined reference to 'stdin'
  ../../../../libs/armeabi-v7a/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'stdin'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.`

**Comment by leenjewel** [comment]
Which Android API version do you use ？

**Comment by dkhanchopoulo** [comment]
android API 21.
I find the reason. It is connected to NDK 15, If i use NDK 14, there is no issue.

**Comment by leenjewel** [comment]
OK cool, I update my readme to explain it
