### ISSUE TITLE
openssl for iOS missing from the already compiled package

### ISSUE THREAD

**Issue by AlterX76** [leenjewel/openssl_for_ios_and_android#4]
I can find only the android version although it says ios and android

**Comment by leenjewel** [comment]
Really？You could download `openssl_curl_for_ios_android.20170105.zip` on releases tab page and unzip it , You will find static library files for android and ios, check it again

**Comment by AlterX76** [comment]
Hi...good now I can see both.
Anyway when I use it (I tried on android) I get few undefined references like SSL_library_init.

**Comment by leenjewel** [comment]
Please show me `Android.mk` and `Application.mk` file in your project

**Comment by AlterX76** [comment]
Ok I solved it, thanks

**Comment by leenjewel** [comment]
Cool，Good luck，I close it
