### ISSUE TITLE
APK包的问题

### ISSUE THREAD

**Issue by weizongwei5** [leenjewel/openssl_for_ios_and_android#7]
问下楼主:
openssl这么大的一个库,不做修改直接编译,然后又以静态库依赖,那导入到apk中,会让apk变大多少?
这个大小是不是超出了承受范围.

**Comment by leenjewel** [comment]
这个和你使用到的 OpenSSL 具体哪些功能有关，除非你在 mk 文件中使用 whole library 来强制将全部静态库导入，否则最终由静态库依赖生成的 so 文件只包含所用到的代码，所以说和你具体的使用是有关系的

具体的你可以通过真是编译来测试一下体积增大的情况，理论上不会很大

**Comment by weizongwei5** [comment]
看你博客写到了demo，目前你打出来的apk是多大呢？

**Comment by leenjewel** [comment]
新增加了 Example ，用 AndroidStudio 写了一个调用 OpenSSL 的示例，你可以参考一下
