### ISSUE TITLE
PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by yzb2016** [leenjewel/openssl_for_ios_and_android#70]
我下载master分支，进入tools文件夹执行下面的脚本后一直报PKG_CONFIG_PATH not defined 请问我应该追加什么配置。
/build-android-openssl.sh arm64    
PKG_CONFIG_PATH not defined

**Comment by leenjewel** [comment]
https://askubuntu.com/questions/210210/pkg-config-path-environment-variable

**Comment by yzb2016** [comment]
实在是抱歉，我看了您发给我的链接上列出的解决方案，也试着做了，但是还解决我的问题。这是我现在的配置，麻烦您帮忙看看。
![截屏2023-04-17 15 37 20](https://user-images.githubusercontent.com/19941251/232417051-3165efcc-37a1-4486-beb4-f8a5dcd01d77.png)

**Comment by yzb2016** [comment]
我通过这个命令find / -type f -name "*.pc" |& grep -iv permission | grep openssl 搜索到了如图所示的.pc的文件。每一个都配置一遍，但是都没有解决问题
![截屏2023-04-17 16 10 39](https://user-images.githubusercontent.com/19941251/232425290-c02a358f-8611-44c5-8595-baf3d199b19c.png)

**Comment by yzb2016** [comment]
我使用这个命令brew install libssl-dev 安装了libssl-dev,还是没有解决问题

**Comment by yzb2016** [comment]
我是第一次接触这个，没有安装pkg- config依赖库😭。所以失败了。我使用brew install pkg-config命令安装了依赖库，然后配置修改成这个：
export PKG_CONFIG_PATH=/opt/homebrew/bin/pkg-config
问题解决了，给您添麻烦了。

**Comment by leenjewel** [comment]
Check List：

- 1 OpenSSL version is openssl-1.1.1i

-2 NDK version is android-ndk-r21d && export $ANDROID_NDK_HOME

My MacOS-X version is 12.6.4 and you?
